### ISSUE TITLE
Cannot Locate Your Data File

### ISSUE THREAD

**Issue by kateblanch** [american-art/autry#1]
Hello!  I'm working on a cross-reference of all the data fields that AAC folks are including in their data sets. This is a general, working document for reference only (nothing final / unchangeable). 
I can't find the Autry's data file...though it appears to have been uploaded. It's in a "revert delete" state?
Can you help me locate it?

Let me know your thoughts. Thanks!

**Comment by caknoblock** [comment]
The user AutryIT deleted the data file.  It has been restored.

**Comment by AutryIT** [comment]
oh. sorry.  I have no idea how I did that.  I'll try to be more careful...
Rebecca
