### ISSUE TITLE
Thesaurus of AutryObjects: ObjectName

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/autry#11]
Does Autry have a dictionary for the terms that suggest object types? This is for the sake of generating a more meaningful URI.

**Comment by AutryIT** [comment]
I have a category field but I'm not sure if it's more meaningful.  I'm pretty sure almost everything in the data set has the same value: Art. I thought these object names were pretty straight forward compared to the rest of my data.  I'm not sure I understand the issue.

**Comment by mayaram00** [comment]
Okay
