### ISSUE TITLE
Preferred object identifier: ObjectURI or URL?

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/autry#12]
Since object URL is provided in the new AutryObject data, which one would you like to be the preferred identifier of the object, the URI (that is composed of ObjectID) or the object URL?

**Comment by caknoblock** [comment]
Since URLs can change, they probably don’t make good URIs for an object.

**Comment by AutryIT** [comment]
Agreed

**Comment by mayaram00** [comment]
We used the objectID for the URI.
