### ISSUE TITLE
Using owl:sameAs to include ULAN ID in the model

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/autry#13]
It seems that not all makers have got ULAN ID; therefore we can't use ULAN ID as maker URI (I'm using the URL instead). In order to include ULAN ID whenever it's available, I propose that we use the 'sameAs' property from OWL ontology (https://www.w3.org/TR/owl-ref/#sameAs-def) to link the two identifiers for the maker.

**Comment by caknoblock** [comment]
Since we will be linking all of the data to ULAN and then creating and curating same-as links, let’s add the ULAN ID from Autry as an additional ID field.  Then we can compare the results of automatically linking to the ones they linked manually.

**Comment by mayaram00** [comment]
Looks resolved.
