### ISSUE TITLE
How to assign URI to the publications in AutryPublication?

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/autry#14]
In AutryPublication, there are WorldCatURL and OCLC_Number fields that could potentially be used as URIs for the publications. However, the issue is that both fields have missing entries for certain objects. In that case, I am not exactly sure how to proceed with the publication URI since having blank URI nodes is not a good practice in general.

**Comment by AutryIT** [comment]
please use OCLC, since worldcat doesn't have all publications.  I will fill in the last few OCLC numbers.  In the meantime, can the row be dropped if the number isn't there?

**Comment by mayaram00** [comment]
This looks as though it was resolved.
