### ISSUE TITLE
AutryDates: Are both earliest and latest year referring to the production?

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/autry#15]
Just to clarify, are both columns referring to the year of production of the particular object?

**Comment by AutryIT** [comment]
Yes.  the two fields together represent the date range within which the object was made.  The range is certain as opposed to the Dated field which expresses the range in a human readable format.  the 3 fields together represent the date the object was made.

**Comment by mayaram00** [comment]
Modeled correctly.
