### ISSUE TITLE
Mapping of AutryCultureMade:Culture

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/autry#2]
I am currently mapping the "Culture" as the Period of production, since it makes sense for the culture to be considered as "a specification of the time period and/ or social culture of the production of the object", according to British Museum mapping guide. 

Does anyone have a better way of treating the "Culture" data? Thanks.

**Comment by AutryIT** [comment]
No. Not in North America.  Native American cultures are absolutely not to be connected with date ranges unless they are associated with certain archaeological materials. Dates must be distinct from cultures.  These are makers, but they are not individuals.  Let's see what the data working group comes up with.  I don't know enough about the CRM.

**Comment by YinyiUSC** [comment]
Thanks for the comments! Okay I see, so the culture should be somehow linked to the maker/actor. I'll look into both CIDOC-CRM and BM guides to see if I can find any clues.

**Comment by AutryIT** [comment]
Hi Yinyi, just checking on the notes and I see culture still associated with Period.  Perhaps I'm misunderstanding how it panned out, but I wanted to check in with you about it.

**Comment by YinyiUSC** [comment]
I apologize for the delay since I've been traveling for the past ten days. I thought I uploaded the latest version but turned out I didn't, and sorry about the confusion. I've just put the files on github. This time I mapped "Culture" as a E74_Group that the Actor belongs to. Please take a look at the model and let me know what you think.

**Comment by mayaram00** [comment]
I think this was resolved last semester.
