### ISSUE TITLE
AutryObjects:ObjectNumber

### ISSUE THREAD

**Issue by steads** [american-art/autry#20]
ObjectNumber: This does not seem to have a mapping. It would seem to be a very important field as it looks like the primary identifier for the artwork and so would form an important access point for integration. E22-> P48 has preferred identifier (is preferred identifier of): E42 Identifier

**Comment by mayaram00** [comment]
It looks to me as though it is not mapped because it was used to form the ObjectURI.

**Comment by caknoblock** [comment]
It is good that it used in the objectURI, but that is not sufficient.  The object number should also be mapped as an identifier so that the data is available.

**Comment by mayaram00** [comment]
Mapped.
