### ISSUE TITLE
AutryObjects:CreditLine

### ISSUE THREAD

**Issue by steads** [american-art/autry#23]
CreditLine: Doesn’t seem to have a mapping. There are hidden events in many of the statements that could, with further analysis, produce a number of instances of E7 Activity and instances of E39 Actor with P14.1 roles in the instances of E7 Activity. If the resources are not available then:-
E22     ->P3 ->E62 String 
    ->P3.1 -> E55 Type {Credit Line Statement}

**Comment by workergnome** [comment]
Using the CRMpc model for these, this could be mapped to RDF as:

```
?entity_uri a crm:E22_Man-Made_Object.

?credit_line a crmpc:PC3_has_note ;
  crmpc:P01_has_domain ?entity_uri;
  crmpc:P03_has_range_literal "the credit line text";
  crmpc:P3.1_has_type <http://vocab.getty.edu/aat/300026687>.
```

Another possible mapping of this could be

```
?entity_uri a crm:E22_Man-Made_Object ;
  crm:P129i_is_subject_of _:credit_line_class .
_:credit_line_class a crm:E33_Linguistic_Object;
  crm:P2_has_type http://vocab.getty.edu/aat/300026687;
  crm:P3_has_note ?credit_line .
```

if you needed to attach additional properties to the credit line.

**Comment by mayaram00** [comment]
Fixed
