### ISSUE TITLE
AutryObjects:Materials

### ISSUE THREAD

**Issue by steads** [american-art/autry#26]
Materials: Fields like this are a perpetual problem. It is a mishmash of many different things lumped together into one field though it is less pronounced than the Medium field in the NPG data set. It is a mixture of technique, mostly general but some specifics, and material(s). To deal with it completely would require a full analysis of each different unique entry string so that they can be divided into those elements that are E29 Design or Procedure (for specific documented techniques), E55 Type (for general techniques) and E57 Materials. Also the relationship needs to be established so that the correct property is used to connect things. Materials that become part of the object use P45 whereas materials that are just used during modification/production would use P126 employed (was employed in). If the resources are available to do this analysis then great, if not then treat it as a simple E55 Type. 
E22 -> P2 ->E55 (Material).
The use of P3 (which should attach to an E62 string perhaps implemented as a literal) is incorrect.

**Comment by mayaram00** [comment]
Used E22-P2-E55.
