### ISSUE TITLE
AutryObjects:Measurements

### ISSUE THREAD

**Issue by steads** [american-art/autry#27]
Measurements: Like the Dimensions field in the NPG data set there is some variability in the format of this field. With analysis and processing 4 to 10 instances of E54 Dimension could be extracted from each entry in this field: metric and imperial; length, breadth and, for 3D works, depth plus the same including the frame. Some of the text flags present in the field might be used to qualify (with an E55 Type) the nature of an associated E16 Measurement. Else treat as a string:-
E22     ->P3 ->E62 String 
    ->P3.1 -> E55 Type {Dimensions Statement}

**Comment by mayaram00** [comment]
Fixed
