### ISSUE TITLE
Question mark contained in AutryCultureMade:Culture

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/autry#3]
The question I have is about the value of this field. For the values that contain a question mark (for example, "Sioux?"), I haven't found a best way to imply the uncertainty. Would it be better if I exclude this piece of information, or if I simply take away the question mark? Thanks.

**Comment by AutryIT** [comment]
Sorry about that. We can change it to "probably Sioux".

**Comment by YinyiUSC** [comment]
I'm sorry but I think I didn't make myself clear. My concern is that, CIDOC-CRM is not perfect for conveying uncertain information such as "probably Sioux". Both URI and relationship in CRM requires accurate information. Therefore, we might have to either disregard the cultural information that contains uncertainty, or make the information certain (probably Sioux -> Sioux). The first option leaves out some information, while the second option risks the accuracy of data.

**Comment by mayaram00** [comment]
I think this was resolved last semester.
