### ISSUE TITLE
AutryDated

### ISSUE THREAD

**Issue by steads** [american-art/autry#30]
The mapping of this table is correct.
It is just worth noting that the Properties P82a and P82b are not part of the CRM standard itself: they are a CRM-SIG approved RDF implementation of the standard. This is nothing to get hung up about; all E61 Time Primitives have to be locally implemented and this implementation choice has the advantage of being one that has been considered Good Practice by the SIG.

**Comment by mayaram00** [comment]
Left unchanged.
