### ISSUE TITLE
AutryMakers_new:ObjectID and Maker

### ISSUE THREAD

**Issue by steads** [american-art/autry#31]
The core path is broadly correct, however the use of E39 Actor is weak compared with using E21 Person and E40 Legal Body (I think Tiffany and Company is the only instance of E40). 
The use of E82 Actor Appellation is incorrect. The Maker field is an appellation of an actor not an instance of E82 Actor Appellation. 
P14 could be extended with P14.1 in the role of E55 Type with a value of “Maker”.
E22 ->P108i ->E12   ->P14 -> E39 (E21/E40)  -> P1 -> E41
            ->P14.1 ->E55 {Maker}
Care should also be taken as the data has not been normalised and could easily create erroneous duplicate instances of E39 (E21/E40).

**Comment by mayaram00** [comment]
Changed.
