### ISSUE TITLE
AutryMakers_new:Dates

### ISSUE THREAD

**Issue by steads** [american-art/autry#32]
Dates: The construct of E39 ->P129i -> E33 ->P3 ->E62 is overly complex and confusing. The correct path should be:-
E39(E21/E40)    ->P3 ->E62
        ->P3.1  -> E55 Type {Maker Dates Statement}
In fact there is a lot more information hidden in this field. 
The birth dates of instances of E21 Person could easily be mapped as:-
E21 ->P98i ->E67 ->P4 ->E52     ->P82 ->E61
                ->P78  ->E50
The date of death of instances of E21 Person could easily be mapped as:-
E21 ->P100i ->E69 ->P4 ->E52    ->P82 ->E61
                ->P78  ->E50
The dates marked as active could be used together with the FRBRoo class of F51 Pursuit. In particular this would cope well with the entry for the instance of E40 Legal Body {Tiffany and Company}.

**Comment by mayaram00** [comment]
Waiting to map this until we figure out E62.

**Comment by mayaram00** [comment]
Could you provide some clarification for what E39(E321/E40) means?

**Comment by steads** [comment]
E39 or its sub-classes E21 and E40

**Comment by mayaram00** [comment]
so just to clarify, I created columns for both birth and death dates. Is it okay to do the suggested mappings directly from E39 Actor since E21 is a sub class?

**Comment by steads** [comment]
No it is not. E39 is not a valid range for the properties P98 and P100. Only E21 is as instances of E40 do not have births and deaths

**Comment by mayaram00** [comment]
Changed
