### ISSUE TITLE
AutryMakers_new:ULAN-ID

### ISSUE THREAD

**Issue by steads** [american-art/autry#34]
ULAN-ID: This is mapped as a simple appellation/identifier (instance of E42 Identifier). I think that this is actually a strong contender for being an instance of E82 Actor Appellation!

**Comment by mayaram00** [comment]
I changed it to E82. This is currently mapped twice: from E22 -> P1 -> E82 and also directly from actor E39 -> P1 -> E82. I think it would make sense to remove the mapping directly from E22 if ULAN_ID is an actor appellation – is there a reason it is mapped also from E22?

**Comment by steads** [comment]
It should not be mapped from E22.

**Comment by mayaram00** [comment]
Removed unnecessary mapping.

**Comment by azaroth42** [comment]
This seems ... very strange to use an Appellation for an Identifier. @steads could you explain the logic here for us please?

**Comment by azaroth42** [comment]
@mayaram00 Could you re-open the issue please until there's agreement about the mapping?  Thanks :)

**Comment by steads** [comment]
All identifiers are appellations. In the case of ULAN-IDs by their very nature we now that they are appellations of actors and so can be mapped to E82 Actor Appellation. The scope notes for E41 Appellation and it's sub classes may make this clearer.

**Comment by azaroth42** [comment]
Unfortunately they don't :) It would be great if you could explain when E42_Identifier would be used rather than one of E41's subclasses or E41 itself?

**Comment by workergnome** [comment]
Additionally, it will be important to indicate that this is a ULAN identifier, as opposed to an institution Party ID or a human name.  Is the appropriate way to do so to use `crm:E55_Type`, and if so, what type should we use; is there one in ULAN to describe it?

Or perhaps `_:ulan_id skos:inScheme ulan: .` would work?

Additionally, is this the ID for the entity in ULAN, or is it the concept?
