### ISSUE TITLE
AutryMakers_new:AutryMakerURL

### ISSUE THREAD

**Issue by steads** [american-art/autry#35]
AutryMakerURL: The URL is another appellation for the Maker and is probably unique and intended to identify individual makers. It should be mapped as
E39(E21/E40) ->P1 ->E42

**Comment by mayaram00** [comment]
Changed.

**Comment by workergnome** [comment]
If you're going to map the URL this way, it should also be typed in some way to distinguish it from other forms of identifiers.  I might suggest http://vocab.getty.edu/aat/300404630 as an appropriate type for this.

Alternately, it might be useful to also emit a `foaf:page` link from the maker to the url, to indicate that the URL represents a web document.
