### ISSUE TITLE
AutryMedia

### ISSUE THREAD

**Issue by steads** [american-art/autry#36]
The mapping for this table can be simply:-
E22 ->P138i ->E38   ->P2 ->E55 {Main} or {Other} (NB not sure how you decide this from the data)
            ->P1 ->E42 [ImageLink]
            ->P3 ->E62 [Caption]
            ->P3.1 ->E55 {Image Caption}
            ->P3 -> E62 [CreditLine]
            ->P3.1 ->E55 {Image CreditLine}

**Comment by mayaram00** [comment]
I still can't seem to find E62 on my Karma – can I use E33 instead or is that insufficient

**Comment by mayaram00** [comment]
Fixed
