### ISSUE TITLE
AutryPubDesc

### ISSUE THREAD

**Issue by steads** [american-art/autry#38]
E22     ->P3 ->E62 String 
    ->P3.1 -> E55 Type {Public Description}

**Comment by mayaram00** [comment]
My version of Karma does not seem to have E62 String. It is currently mapped with E33 Linguistic Object - is this sufficient?

**Comment by caknoblock** [comment]
The issue is that they are not in the cidoc-crm-v6.2 onotology that we are using.  @steads, is there are reason that E62 is not defined in the ontology?

**Comment by mayaram00** [comment]
Downloaded CRM-pc and applied 3.1 through that as discussed
