### ISSUE TITLE
AutryPublications

### ISSUE THREAD

**Issue by steads** [american-art/autry#39]
I suspect that the publications referred to here are not intended to scientifically document the objects in the collection but are actually general works that refer to the objects in the collection. The Title field is closer to a controlled access point rather than an instance of E35 Title as they contain author, volume and date information. The WorldCatURL and OCLC-Number are both characteristic forms of appellation applied to these instances of E28 Conceptual Object and so qualify as instances of E75 Conceptual Object Appellation. Where Pages are present there should be a component relationship to the whole publication, otherwise the P148 has component (is component of) part of the path can be omitted:
So the path were Pages are present is:-
E22 ->P67i ->E73 [Pages]     ->P1 -> E41 [Pages]
                ->P148 ->E73 [Title]    ->P1 ->E42 [Title]
                            ->P149 ->E75 [WorldCatURL]
                            ->P149 ->E75 [OCLC_Number]
 
So the path were Pages are not present is:-
E22 ->P67i  ->E73 [Title]   ->P1 ->E42 [Title]
                ->P149 ->E75 [WorldCatURL]
                ->P149 ->E75 [OCLC_Number]
More detailed modelling of the bibliographic records could be done using FRBRoo but given the LOD links are already provided to World Cat and OCLC there seems little point in wasting effort duplicating their work.

**Comment by mayaram00** [comment]
Since some have pages and some don't, which one should I use?

**Comment by caknoblock** [comment]
You can make them both ways.  Use a select to filter out the ones with pages and then map that as indicated.  Then use a select to filter out the ones without pages and map those.

**Comment by mayaram00** [comment]
I created two mappings for the same dataset; one with pages and one without.
