### ISSUE TITLE
Thesaurus of AutryCultureMade: Culture

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/autry#4]
I would like to know if Autry has its thesaurus for cultural terms. That would help me create URIs for them such as autry/thesauri/culture/Sioux. Thanks.

**Comment by AutryIT** [comment]
There are a lot of vocabularies around related to Native American cultures.  It is a very controversial topic. Let's not link for now.  Sorry.

**Comment by YinyiUSC** [comment]
okay, thanks.
