### ISSUE TITLE
AutryObjects: Owner URL

### ISSUE THREAD

**Issue by rhao** [american-art/autry#40]
AutryObjects has data about the owner url (for example, https://theautry.org), but the http://review.americanartcollaborative.org/ site doesn't have info on this. I'm ignoring the column for now, but if there's a way I should map that, let me know.

**Comment by workergnome** [comment]
the owner is just another form of actor, and use the actor primary webpage pattern for that.

http://review.americanartcollaborative.org/entity/E39_Actor#field_19-search_0

**Comment by kateblanch** [comment]
@rhao -- let me know if David's reply was enough to get you moving on this or if you need more information from me or the Autry. Thanks!

**Comment by rhao** [comment]
David's comment answered my question, but thanks for checking in!
