### ISSUE TITLE
General question: object materials

### ISSUE THREAD

**Issue by rhao** [american-art/autry#44]
What is the difference between <material_name> and <lod_material_term>?

Also, most of the data I've seen for material is more of a description instead of a one word material. For example, "Lithograph print on paper, original hand coloring" or "Oil on canvas, gilded wooden frame". Is that okay? It seems like it would be better to create a material class instance tied to "paper" or "wood" or something, but the data isn't like that.

**Comment by workergnome** [comment]
Material name is the name of a material.  "Wood",  "Paper", etc.

LOD_material_term is an AAT term for that material.

Medium Text (http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_15-search_0) is where the english string for something like  "Lithograph print on paper, original hand coloring" would go.

**Comment by rhao** [comment]
Awesome thanks!
