### ISSUE TITLE
AutryMakers: Nationality

### ISSUE THREAD

**Issue by rhao** [american-art/autry#46]
I was going to map the Nationality column as the Actor Nationality (http://review.americanartcollaborative.org/entity/E39_Actor#field_13-search_0), but I have a few questions:

1. It doesn't seem like all the data are actually nationalities (for example: "Navajo" or "San Ildefonso Pueblo (Tewa)"). Should I still map it as Nationality?

2. How should I parse entries that aren't just one single nationality? For example:
a) "Wiyot and Yurok"
b) "born Germany, active United States"
Can I just make the entire thing the rdfs:label of the E74_Group, or do I have to do more parsing?

**Comment by workergnome** [comment]
For this project, I'd map them all as nationalities and not do more parsing.  If the Autry would like more specific names, they can modify their data or provide rules.

(This is more in the interests of expediency than correctness—I'd *love* for you to parse these into proper semantic meanings, but I'd rather you get through more datasets.)

**Comment by rhao** [comment]
Works for me.
