### ISSUE TITLE
AutryMakers: Dates

### ISSUE THREAD

**Issue by rhao** [american-art/autry#47]
The dates column format is pretty varied (for example: "1914-1994", "born 1965", "active mid-19th century"). For the sake of the artist, to get the birth and death years, I accepted "yyyy-yyyy" and "born yyyy". I ignored all rows that contain 'founded', 'circa', 'active', or 'established'.

Should I have counted the established and founded years as the birth dates? And the active years if it is the format "active yyyy-yyyy" as the birth and death years?

**Comment by workergnome** [comment]
I would use whatever exists there as "display date", and ones that you understand, parse those into earliest and latest.

**Comment by edgartdata** [comment]
Not sure if that's helpful here but for cases when you have only the year of birth, it is conventional for museums to estimate the year of death/latest date as year of birth + 100 years. I believe that is what the Categories for the Description of Works of Art recommends.

**Comment by workergnome** [comment]
My preference, though not requirement, is that we don't add estimates like that into the data unless we've got a way to indicate that it's an estimate—otherwise, there's no way to distinguish between 100 year old people and people who we don't know their death date.

**Comment by caknoblock** [comment]
I agree.  If we don’t know the date, we should leave it blank.

**Comment by rhao** [comment]
It seemed a bit odd to use whatever exists in the column as both the <display_birthdate> and the <display_deathdate> (there isn't a generic <display_date> in review.aac that I noticed, so I parsed into birth and death years where I could and used Jan 1 and Dec 31 as earliest and latest birth/death dates. If no death date was specified, I left it blank instead of adding 100 years.
