### ISSUE TITLE
AutryMakers: Birth and Death

### ISSUE THREAD

**Issue by rhao** [american-art/autry#48]
The data only has years, no month or day. I am following this model: http://review.americanartcollaborative.org/entity/E39_Actor#field_14-search_0

Can I just make the year the <display_birthdate> and exclude <latest_birthdate> and <earliest_birthdate>? If not, should earliest and latest birthdate be:
1. yyyy and yyyy
2. 01-01-yyyy and 12-31-yyyy
3. same as 2, but make it an xsd:date literal

**Comment by workergnome** [comment]
3 would be my preference?

**Comment by rhao** [comment]
Great, I followed 3.
