### ISSUE TITLE
URI of AutryMakers: Maker

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/autry#5]
Is it possible for Autry to include the constituent ID for the makers? I could use them to construct the maker URIs. If not, I will use the names of the makers instead, but a unique ID would be more preferable. Thanks.

**Comment by AutryIT** [comment]
Yes.  I thought we were going to link to ULAN.  I was hoping for an automated way to do it, but I'll go through and enter the data and send it over.  It may take me a couple weeks.  What was the deadline again?

**Comment by caknoblock** [comment]
As soon as possible, but we need all data by the end of February at the latest.

**Comment by AutryIT** [comment]
Do you want the ULAN ID or the URL for the artist?  For example, Tony Abeita could be
http://www.getty.edu/vow/ULANFullDisplay?find=tony+abeyta&role=&nation=&prev_page=1&subjectid=500126291
or simply
500126291

**Comment by caknoblock** [comment]
Just the id number is sufficient.  And if you have these for ULAN, that is great.  But what Yinyi wanted was something simpler, which is just the internal ID number that you assign to each artist in your own collection.

**Comment by AutryIT** [comment]
No problem. I can do both.

**Comment by mayaram00** [comment]
Data was provided and we have included it in the model.
