### ISSUE TITLE
Error with MediumText query

### ISSUE THREAD

**Issue by rhao** [american-art/autry#51]
The diagram says it should be an E33_LinguisticObject so I modeled it as that, but when I look at the query it is looking for an E57_Material. If LinguisticObject is incorrect, let me know because the model will have to be updated.

http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_15-search_0

**Comment by workergnome** [comment]
That's a mistake—good catch.  It is supposed to be an E33.  Fixed.
