### ISSUE TITLE
Two different URIs for the same object

### ISSUE THREAD

**Issue by workergnome** [american-art/autry#53]
http://data.americanartcollaborative.org/autry/object/98561
http://data.americanartcollaborative.org/autry/object/98_56_1

both appear to refer to the same object

**Comment by AutryIT** [comment]
I'm not sure how this happened. But I imagine if it occurs with this record, it probably appears with all.

**Comment by workergnome** [comment]
I think it's just two different sections of the mapping using different URI patterns.

**Comment by AutryIT** [comment]
Can someone from ISI help me pinpoint this duplication in the mapping?

**Comment by workergnome** [comment]
I think it's in ISI's mapping of your data, not in your export.  It's likely just a typo in the Karma mapping, and easily resolved.

**Comment by bsnikhila** [comment]
Fixed it

**Comment by workergnome** [comment]
Does not appear to be fixed (or at least is manifesting differently)...

http://data.americanartcollaborative.org/page/autry/object/2008.11.1
and
http://data.americanartcollaborative.org/page/autry/object/2008111

**Comment by bsnikhila** [comment]
It should be fixed now

**Comment by workergnome** [comment]
Confirmed fixed.  Thank you.
