### ISSUE TITLE
Autry Maker dates

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/autry#57]
Examples from AutryMakers.csv (Maker: Dates):
- Abeyta, Tony:	born 1965
- Arroyo Hondo Carver:	active 1825-1850
- Beechey, Richard Brydges:	1808-1895

I checked these 
- http://data.americanartcollaborative.org/autry/maker/abeytatony
- http://data.americanartcollaborative.org/autry/maker/arroyohondocarver
- http://data.americanartcollaborative.org/autry/maker/beecheyrichardbrydges

The first one has empty birth_event and death_event, without any data.

I assume that you're not parsing the Dates field. If so then it's incorrect to make birth/death events.
The best you can do is make a "life" event, eg something like this. 
```ttl
<maker> crm:P14i_performed <maker/life>.
<maker/life> a crm:E7_Activity;
  crm:p2_has_type aat:300055134; "life". Or else 300393178 "floruit"
  crm:p3_has_note "born 1965". # or active 1825-1850, etc
```
You could push the Dates field further down into a Time-Span, but I don't see any benefit

@workergnome, would this be useful to you?

**Comment by workergnome** [comment]
Could be useful, if it's all we're going to get.

**Comment by VladimirAlexiev** [comment]
@rhao in #47 describes what she did, and she parses dates. But the result (see the 3 links on top of this issue) is not that: we just got Birth & Death nodes, with no info.

"Active" (flourit) is definitely not the same as "Life" (birth/death), so please don't assume you should make birth & death nodes. Here's a breakdown if you want to make it precise
```
     72 born DDDD              # birth
     90 DDDD-DDDD           # birth-death, or E7_Activity with aat:300055134; "life"
      2 Established DDDD     # E66_Formation
      5 active DDDD-DDDD  # E7_Activity with 300393178 "floruit"
      5                                   # DO NOT make any events
      1 active DDDD-present
      1 active mid-DDth century
      1 born DDDD; active DDDD-DDDD
      1 born circa DDDD
      1 circa DDDD-DDDD
      1 founded DDDD
      1 DDDD DDDD
```

**Comment by bsnikhila** [comment]
I removed the time-span when there is no birth or death date.
