### ISSUE TITLE
Autry Maker ID

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/autry#58]
AutryMakers.csv have home page URLs like http://collections.theautry.org/mwebcgi/mweb.exe?request=record;id=PE26890;type=701.
Please extract the ID from there (eg PE26890) and emit it as actor ID.

@workergnome needs that for the display app

**Comment by bsnikhila** [comment]
Added.
http://data.americanartcollaborative.org/page/autry/maker/readthomasbuchanan
