### ISSUE TITLE
Inconsistent data values in AutryMakers: Dates

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/autry#6]
I noticed there are quite a lot of differently-formatted values in this column, for example:

born xxxx
active xxxx-xxxx
xxxx-xxxx
active mid-19th century
born xxxx; active xxxx-xxxx
circa xxxx
born circa xxxx
founded xxxx
established xxxx
etc.

Since I haven't seen the complete dataset, the list might still go on. It would be a little bit challenging to clean the data and extract only numeric values for birth/death or begin/end date. Would it be okay if I consider the "Dates" to be a note to the person or institution? If not, how would you suggest I clean the data? Thanks.

**Comment by AutryIT** [comment]
Yes.  This should be a note.  As you can see, I treat it as such.  Hopefully, our link to ULAN will take care of the specific date problem.

**Comment by YinyiUSC** [comment]
Got it, thanks!
