### ISSUE TITLE
sanitize Autry descriptions

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/autry#60]
@bsnikhila AutryPubDesc.xlsx has this one (broken to several lines for readability):
```Sculpture by Richard V. Greeves, <em>Crazy Horse</em>, 1997. 
Signed and dated. Carved around the base: <em>Killed 1877 Defending His Country</em>, 
<em>American Hero<em>, and <em>Crazy Horse</em>.
```
Nice and dandy but one of them `<em>`s is unclosed. 
You can see it at http://data.americanartcollaborative.org/page/autry/object/200981, where half the page is italic.
Bet this will make @workergnome's life interesting.

One of you'all must sanitize this, I think by removing HTML tags.

**Comment by workergnome** [comment]
Yeah—I've seen this sort of thing.  I've been allowing HTML tags, because they're usually useful enough that I'm willing to take the hit for typos in their data, but this one should probably be fixed in the data.

**Comment by AutryIT** [comment]
Ready to close, the fix will appear in our updated data set to be submitted August 25
