### ISSUE TITLE
Autry Culture classification is incomplete

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/autry#61]
Compare these two clasifications of the same object:
- http://data.americanartcollaborative.org/page/autry/object/89541/culture
- http://data.americanartcollaborative.org/page/autry/object/89541/classification_event/necklace

The first one is missing P2_has_type. Since that comes from AutryCultureMade.xlsx, use aat:300015646 "Styles and Periods".

**Comment by bsnikhila** [comment]
Added P21_had_general_purpose according to the review site.
