### ISSUE TITLE
Use Autry "Object Name" when there's no Title

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/autry#62]
http://data.americanartcollaborative.org/page/autry/object/89541 is a bear claw necklace, but has two weird titles:
<http://data.americanartcollaborative.org/autry/thesauri/title/autrymuseumofwesternheritagebrochure1999>
<http://data.americanartcollaborative.org/autry/thesauri/title/convergencespringsummer2005>

These come from AutryPublications.xlsx.
Publications are decidedly not Titles.

I think the current decision is to drop publications. Else, they can be mapped similar to [Catalogue Raisonné]( http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_31-search_0)

**Comment by VladimirAlexiev** [comment]
@mayaram00: Related to #39

**Comment by AutryIT** [comment]
It would be a pity to drop the publications because they are mapped to WorldCat.  How about if we simply drop the title?

**Comment by VladimirAlexiev** [comment]
Right, eg one pub record is
```
88.108.1	
American genre painting: the politics of everyday life by Elizabeth Johns.	
p. 81	
http://www.worldcat.org/oclc/23213978	
ocm23213978
```
Its home page is http://collections.theautry.org/mwebcgi/mweb.exe?request=record;id=ocm23213978;type=106, and you can see the related object there.
(http://www.worldcat.org/oclc/23213978 may be called a home page of the whole book)

@AutryIT: If you look at the above URLs, you'll see there's neither Worldcat nor OCLC numbers. Dropping the object title but keeping the publication title is not an option, it'd just be wrong

The AAC decision was to drop Publications because of lack of time/effort (cc @caknoblock @azaroth42 @workergnome).

**Comment by kateblanch** [comment]
Where an object has both it's own title and an associated publication title, it is not returning rightly in the browse app validator. Publications need an entirely different data model than the Object Title. @edgartdata  helped up map this for a different project using E22_Man_Made_Object - P70i_is_documented_in - E31_Document. 

WHat is the best way to clear up this problem? We can drop the Publications file, but should we delete it from GitHub? How do we clear this out of the SPARQL endpoint?

**Comment by kateblanch** [comment]
Also, why is title text part of the URI? This seems to be mirroring what is wrong with the Credit Line mapping. 

@AutryIT and I are talking this over, and it seems like perhaps the text strings were used in the URIs because the items (credit line, title, culture) did not have unique IDs and sometimes multiple items exist per object. Rebecca at the Autry can add IDs to the data to correct this and get to the desired URI pattern (e.g. http://data.thewalters.org/object/10264/title/20961) but data modeling would need to be changed. 
@caknoblock - can you advise us in part with your student team whether this is possible/necessary?

**Comment by bsnikhila** [comment]
I have removed the data from the Publications file from the triple store for now. I will add it back once a mapping has been decided for it.

**Comment by VladimirAlexiev** [comment]
Now the object doesn't have a title.
(It also doesn't have a creator, please check if there is one in the data)

**Comment by AutryIT** [comment]
Ready to close, since publications weren't used

**Comment by VladimirAlexiev** [comment]
@AutryIT I checked several of your objects, and none of them have titles in RDF. That's a problem since the browse app wants to show the title.
- many objects in your system don't have title. But in that case the Object Name should be used, just like on your website. Eg:
Object Name="bulto": http://data.americanartcollaborative.org/page/autry/object/153l7 http://collections.theautry.org/mwebcgi/mweb.exe?request=record;id=M201907;type=101
Object Name="carving": http://data.americanartcollaborative.org/page/autry/object/883681 http://collections.theautry.org/mwebcgi/mweb.exe?request=record;id=M557746;type=101 
- many objects from your website are not in the RDF data, I guess that is on purpose?
title="Colonel Crockett [graphic]" http://collections.theautry.org/mwebcgi/mweb.exe?request=record;id=CGAV01-F48;type=101
Object Name="blanket": http://collections.theautry.org/mwebcgi/mweb.exe?request=record;id=M92570;type=101
  - in particular I couldn't find an object with Title in RDF

How do I go from website to RDF: go to http://yasgui.org/short/HJXszbvPW and substitute the website URL in the query

**Comment by VladimirAlexiev** [comment]
I found an object with title, http://data.americanartcollaborative.org/page/autry/object/881084.
So I'll change this issue to say that Object Name should also be used

**Comment by VladimirAlexiev** [comment]
There are 193 objects with owner Autry: http://yasgui.org/short/HknwB5tDZ
Of them 165 have a title: http://yasgui.org/short/HyELLqFwZ

**Comment by AutryIT** [comment]
Hi folks, do you need my input on this one?  How about this: I will put the object name in the title field wherever we don't have a title when I refresh the data.  We can go ahead and close this issue.

**Comment by VladimirAlexiev** [comment]
@AutryIT Sounds like a plan. But close it only when you see the above objects get a title in RDF.
(PS: CCO calls a title derived from the object name "descriptive title")

Cheers!

**Comment by AutryIT** [comment]
I am using the same field as the title field so as not to add anything new.  So I will leave the map as is.  I've put the titles in brackets to indicate they are derived.
