### ISSUE TITLE
Credit line duplicated in Browse app

### ISSUE THREAD

**Issue by AutryIT** [american-art/autry#64]
Quick question - we see our credit line duplicated in some of our records in the Browse app (for example: http://aac-browse-dev.netlify.com/object/autry/200041.html), but we don't see the same duplication on the data proofing site (the same record is: http://data.americanartcollaborative.org/page/autry/object/200041/credit_line).  Can you help us understand where the duplication in the Browse app is coming from?

**Comment by workergnome** [comment]
Might be old data.  The browse app doesn't pull live data from the triple store for performance reasons, so I need to manually refresh it once things are fixed.

 Let me re-load from the triple store and see if that fixes it.

**Comment by workergnome** [comment]
That was the problem—should be resolved in the next hour or so once the site's re-uploaded.
