### ISSUE TITLE
Link Curation

### ISSUE THREAD

**Issue by AutryIT** [american-art/autry#65]
We found three makers in the link curation tool which had the incorrect mapping.  The correct mapping for these three makers is in our data, and it appears correctly in the record on: http://data.americanartcollaborative.org

Is there a need to correct the incorrect assumption from link curation?

**Comment by caknoblock** [comment]
I assume that if you found an incorrect mapping in the link curation tool, then you selected the option “No”.  That is the record that says it is not a match.  Once the curation is completed, we will compare the results against the ULAN records provided by Autry.
