### ISSUE TITLE
Mapping of AutryMedia: SortOrder

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/autry#7]
I am not exactly sure what information SortOrder conveys apart from the fact that it is used to distinguish several images that represent a same object. Would it be okay if I leave it out of the model? Thanks.

**Comment by AutryIT** [comment]
Well. I tend to have a lot of images per object.  It's kind of confusing to see the wrong image show up as primary.  But if that's what's going to happen in the LOD world, I can live with it.  Maybe the data working group will have an idea.  I'm sure I'm not the only one with this issue.

**Comment by caknoblock** [comment]
We need to figure out how to indicate the preferred image in CIDOC-CRM.

**Comment by YinyiUSC** [comment]
We've been using skos:prefLabel and crm:preferred-identifier, but both are for text strings rather than images. British museum used extension (PX_has_main_representation) to designate the main image for the object where more than one published image is available an extension has been used. But using extended properties is probably not the most desired way. Currently I'm using the BM extension PX_has_main_representation.

**Comment by mayaram00** [comment]
I think this was resolved last semester.
