### ISSUE TITLE
Autry objects don't have current_owner

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/autry#72]
None of the Autry objects point back to the Autry. 
Eg http://data.americanartcollaborative.org/page/autry/object/883681

**Comment by workergnome** [comment]
Was this fixed?  I see 

crm:P52_has_current_owner <http://data.americanartcollaborative.org/autry>

on that page

**Comment by VladimirAlexiev** [comment]
Oh, I must be blind.
@AutryIT you only got 193, is that right? http://yasgui.org/short/HknwB5tDZ

**Comment by bsnikhila** [comment]
All objects seem to have the owner data. Am I missing anything?

**Comment by VladimirAlexiev** [comment]
Wrong bug report. I checked their source data, they got 193 objects, and all have owner
