### ISSUE TITLE
Mapping of AutryObjects: Materials

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/autry#8]
Some sample entries of "Materials" are:

Oil on canvas
Pencil and watercolor on paper
Bear claws and trade beads strung on leader thong, decorated with beaver fur and red ochre
etc.

I used to map this field as E29 Design or Procedure (http://139.91.183.82:8888/drupal/Entity/E29-Design-or-Procedure/Version-6.0), but I was told that the description is more about what the artwork is made of, rather than the design. Therefore, I propose that we use E57 Materials (http://83.212.168.219/CIDOC-CRM/Entity/e57-material/version-6.0), and then E22 Man-made Objects will be connected to E57 Materials via P46 is composed of (http://83.212.168.219/CIDOC-CRM/Property/p46-is-composed-of/version-6.0). Does anyone have other suggestions?

**Comment by AutryIT** [comment]
In my opinion, materials and techniques should not be separated.  I am aware that this is not a popular stand.  I like your solution.
